export const allProducts = [
    {id: 1, name: "Iron Non Stick Dishes", img: "./images/kitchenApp1.PNG"},
    {id: 2, name: "Cooking Stove (Cabinet)", img: "./images/KitchenCabinet.PNG"},
    {id: 3, name: "Cutter Board", img: "./images/KitchenCutter.PNG"},
    {id: 4, name: "Plates and Dishes", img: "./images/KitchenDishes.PNG"},
    {id: 5, name: "Kitchen Equipment", img: "./images/KitchenEqp1.PNG"},
    {id: 6, name: "Grilled Machine", img: "./images/KitchenGrilled.PNG"},
    {id: 7, name: "Grinder and Accessories", img: "./images/KitchenGrinder.PNG"},
    {id: 8, name: "Steel Knifes", img: "./images/KitchenKnife.PNG"},
    {id: 9, name: "Owens", img: "./images/KitchenOwen.PNG"},
    {id: 10, name: "Cook Serving Stand", img: "./images/KitchenServingStand.PNG"},
    {id: 11, name: "Spices Round Rack", img: "./images/KitchenSpiceRack.PNG"},
    {id: 12, name: "Spices Rack", img: "./images/KitchenStand.PNG"},
    {id: 13, name: "Towel", img: "./images/linenroll2.PNG" },
    {id: 14, name: "Bed Accessories", img: "./images/linen1.PNG" },
    {id: 15, name: "Blankets", img: "./images/linenblanket.PNG" },
    {id: 16, name: "Night Dresses", img: "./images/linennightdress.PNG" },
    {id: 17, name: "Foot Mate", img: "./images/linenpad.PNG" },
    {id: 18, name: "Bed Mattress", img: "./images/linenspanching.PNG" },
    {id: 19, name: "Table Cloth Cover", img: "./images/linentablesheet.PNG" },
]